/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef inter_TYPES_H
#define inter_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




struct AGGREGATE {
  enum type {
    AF_SUMMARY = 0,
    AF_MINIMUM = 1,
    AF_MAXIMUM = 2,
    AF_AVERAGE = 3,
    AF_COUNT = 4,
    AF_SUMMARY_FOR_CONTINOUS = 5,
    AF_AVERAGE_FOR_CONTINOUS = 6
  };
};

extern const std::map<int, const char*> _AGGREGATE_VALUES_TO_NAMES;

class DEVICE;

class TAGVAL;

class TAGNODE;

typedef struct _DEVICE__isset {
  _DEVICE__isset() : name(false), id(false) {}
  bool name :1;
  bool id :1;
} _DEVICE__isset;

class DEVICE {
 public:

  static const char* ascii_fingerprint; // = "1CCCF6FC31CFD1D61BBBB1BAF3590620";
  static const uint8_t binary_fingerprint[16]; // = {0x1C,0xCC,0xF6,0xFC,0x31,0xCF,0xD1,0xD6,0x1B,0xBB,0xB1,0xBA,0xF3,0x59,0x06,0x20};

  DEVICE(const DEVICE&);
  DEVICE& operator=(const DEVICE&);
  DEVICE() : name(), id(0) {
  }

  virtual ~DEVICE() throw();
  std::string name;
  int64_t id;

  _DEVICE__isset __isset;

  void __set_name(const std::string& val);

  void __set_id(const int64_t val);

  bool operator == (const DEVICE & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const DEVICE &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DEVICE & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const DEVICE& obj);
};

void swap(DEVICE &a, DEVICE &b);

typedef struct _TAGVAL__isset {
  _TAGVAL__isset() : name(false), timestamp(false), state(false), type(false), value(false), hwnd(false), id(false), device(false) {}
  bool name :1;
  bool timestamp :1;
  bool state :1;
  bool type :1;
  bool value :1;
  bool hwnd :1;
  bool id :1;
  bool device :1;
} _TAGVAL__isset;

class TAGVAL {
 public:

  static const char* ascii_fingerprint; // = "C074D958F71BCFB98527B8D304204C37";
  static const uint8_t binary_fingerprint[16]; // = {0xC0,0x74,0xD9,0x58,0xF7,0x1B,0xCF,0xB9,0x85,0x27,0xB8,0xD3,0x04,0x20,0x4C,0x37};

  TAGVAL(const TAGVAL&);
  TAGVAL& operator=(const TAGVAL&);
  TAGVAL() : name(), timestamp(0), state(0), type(0), value(), hwnd(0), id(0), device() {
  }

  virtual ~TAGVAL() throw();
  std::string name;
  int64_t timestamp;
  int64_t state;
  int16_t type;
  std::string value;
  int64_t hwnd;
  int64_t id;
  std::string device;

  _TAGVAL__isset __isset;

  void __set_name(const std::string& val);

  void __set_timestamp(const int64_t val);

  void __set_state(const int64_t val);

  void __set_type(const int16_t val);

  void __set_value(const std::string& val);

  void __set_hwnd(const int64_t val);

  void __set_id(const int64_t val);

  void __set_device(const std::string& val);

  bool operator == (const TAGVAL & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(state == rhs.state))
      return false;
    if (!(type == rhs.type))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(hwnd == rhs.hwnd))
      return false;
    if (!(id == rhs.id))
      return false;
    if (!(device == rhs.device))
      return false;
    return true;
  }
  bool operator != (const TAGVAL &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TAGVAL & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TAGVAL& obj);
};

void swap(TAGVAL &a, TAGVAL &b);

typedef struct _TAGNODE__isset {
  _TAGNODE__isset() : name(false), desc(false), engUnit(false), id(false), type(false), IOState(false), typicalVal(false), value(false), enumDesc(false), timestamp(false), state(false), deviceName(false), groupName(false), sourceTag(false), upperLimit(false), lowerLimit(false), pushreference(false), ruleReference(false), exceptionMin(false), exceptionMax(false), exceptionDev(false), alarmType(false), alarmState(false), alarmHi(false), alarmLo(false), alarmHiHi(false), alarmLolo(false), hiPriority(false), loPriority(false), hihiPriority(false), loloPriority(false), isArchived(false), isCompressed(false), interMethod(false), hisIndex(false), compressMin(false), compressMax(false), lastValue(false), creationDate(false) {}
  bool name :1;
  bool desc :1;
  bool engUnit :1;
  bool id :1;
  bool type :1;
  bool IOState :1;
  bool typicalVal :1;
  bool value :1;
  bool enumDesc :1;
  bool timestamp :1;
  bool state :1;
  bool deviceName :1;
  bool groupName :1;
  bool sourceTag :1;
  bool upperLimit :1;
  bool lowerLimit :1;
  bool pushreference :1;
  bool ruleReference :1;
  bool exceptionMin :1;
  bool exceptionMax :1;
  bool exceptionDev :1;
  bool alarmType :1;
  bool alarmState :1;
  bool alarmHi :1;
  bool alarmLo :1;
  bool alarmHiHi :1;
  bool alarmLolo :1;
  bool hiPriority :1;
  bool loPriority :1;
  bool hihiPriority :1;
  bool loloPriority :1;
  bool isArchived :1;
  bool isCompressed :1;
  bool interMethod :1;
  bool hisIndex :1;
  bool compressMin :1;
  bool compressMax :1;
  bool lastValue :1;
  bool creationDate :1;
} _TAGNODE__isset;

class TAGNODE {
 public:

  static const char* ascii_fingerprint; // = "E3329B9DCCD0AB0D88898222DFFA3D92";
  static const uint8_t binary_fingerprint[16]; // = {0xE3,0x32,0x9B,0x9D,0xCC,0xD0,0xAB,0x0D,0x88,0x89,0x82,0x22,0xDF,0xFA,0x3D,0x92};

  TAGNODE(const TAGNODE&);
  TAGNODE& operator=(const TAGNODE&);
  TAGNODE() : name(), desc(), engUnit(), id(0), type(0), IOState(0), typicalVal(0), value(), enumDesc(), timestamp(0), state(0), deviceName(), groupName(), sourceTag(), upperLimit(0), lowerLimit(0), pushreference(0), ruleReference(0), exceptionMin(0), exceptionMax(0), exceptionDev(0), alarmType(0), alarmState(0), alarmHi(0), alarmLo(0), alarmHiHi(0), alarmLolo(0), hiPriority(0), loPriority(0), hihiPriority(0), loloPriority(0), isArchived(0), isCompressed(0), interMethod(0), hisIndex(0), compressMin(0), compressMax(0), lastValue(0), creationDate(0) {
  }

  virtual ~TAGNODE() throw();
  std::string name;
  std::string desc;
  std::string engUnit;
  int64_t id;
  int16_t type;
  int16_t IOState;
  double typicalVal;
  std::string value;
  std::string enumDesc;
  int64_t timestamp;
  int64_t state;
  std::string deviceName;
  std::string groupName;
  std::string sourceTag;
  double upperLimit;
  double lowerLimit;
  int16_t pushreference;
  int16_t ruleReference;
  int64_t exceptionMin;
  int64_t exceptionMax;
  double exceptionDev;
  int16_t alarmType;
  int16_t alarmState;
  double alarmHi;
  double alarmLo;
  double alarmHiHi;
  double alarmLolo;
  int16_t hiPriority;
  int16_t loPriority;
  int16_t hihiPriority;
  int16_t loloPriority;
  bool isArchived;
  bool isCompressed;
  bool interMethod;
  int64_t hisIndex;
  int64_t compressMin;
  int64_t compressMax;
  double lastValue;
  int64_t creationDate;

  _TAGNODE__isset __isset;

  void __set_name(const std::string& val);

  void __set_desc(const std::string& val);

  void __set_engUnit(const std::string& val);

  void __set_id(const int64_t val);

  void __set_type(const int16_t val);

  void __set_IOState(const int16_t val);

  void __set_typicalVal(const double val);

  void __set_value(const std::string& val);

  void __set_enumDesc(const std::string& val);

  void __set_timestamp(const int64_t val);

  void __set_state(const int64_t val);

  void __set_deviceName(const std::string& val);

  void __set_groupName(const std::string& val);

  void __set_sourceTag(const std::string& val);

  void __set_upperLimit(const double val);

  void __set_lowerLimit(const double val);

  void __set_pushreference(const int16_t val);

  void __set_ruleReference(const int16_t val);

  void __set_exceptionMin(const int64_t val);

  void __set_exceptionMax(const int64_t val);

  void __set_exceptionDev(const double val);

  void __set_alarmType(const int16_t val);

  void __set_alarmState(const int16_t val);

  void __set_alarmHi(const double val);

  void __set_alarmLo(const double val);

  void __set_alarmHiHi(const double val);

  void __set_alarmLolo(const double val);

  void __set_hiPriority(const int16_t val);

  void __set_loPriority(const int16_t val);

  void __set_hihiPriority(const int16_t val);

  void __set_loloPriority(const int16_t val);

  void __set_isArchived(const bool val);

  void __set_isCompressed(const bool val);

  void __set_interMethod(const bool val);

  void __set_hisIndex(const int64_t val);

  void __set_compressMin(const int64_t val);

  void __set_compressMax(const int64_t val);

  void __set_lastValue(const double val);

  void __set_creationDate(const int64_t val);

  bool operator == (const TAGNODE & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(desc == rhs.desc))
      return false;
    if (!(engUnit == rhs.engUnit))
      return false;
    if (!(id == rhs.id))
      return false;
    if (!(type == rhs.type))
      return false;
    if (!(IOState == rhs.IOState))
      return false;
    if (!(typicalVal == rhs.typicalVal))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(enumDesc == rhs.enumDesc))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(state == rhs.state))
      return false;
    if (!(deviceName == rhs.deviceName))
      return false;
    if (!(groupName == rhs.groupName))
      return false;
    if (!(sourceTag == rhs.sourceTag))
      return false;
    if (!(upperLimit == rhs.upperLimit))
      return false;
    if (!(lowerLimit == rhs.lowerLimit))
      return false;
    if (!(pushreference == rhs.pushreference))
      return false;
    if (!(ruleReference == rhs.ruleReference))
      return false;
    if (!(exceptionMin == rhs.exceptionMin))
      return false;
    if (!(exceptionMax == rhs.exceptionMax))
      return false;
    if (!(exceptionDev == rhs.exceptionDev))
      return false;
    if (!(alarmType == rhs.alarmType))
      return false;
    if (!(alarmState == rhs.alarmState))
      return false;
    if (!(alarmHi == rhs.alarmHi))
      return false;
    if (!(alarmLo == rhs.alarmLo))
      return false;
    if (!(alarmHiHi == rhs.alarmHiHi))
      return false;
    if (!(alarmLolo == rhs.alarmLolo))
      return false;
    if (!(hiPriority == rhs.hiPriority))
      return false;
    if (!(loPriority == rhs.loPriority))
      return false;
    if (!(hihiPriority == rhs.hihiPriority))
      return false;
    if (!(loloPriority == rhs.loloPriority))
      return false;
    if (!(isArchived == rhs.isArchived))
      return false;
    if (!(isCompressed == rhs.isCompressed))
      return false;
    if (!(interMethod == rhs.interMethod))
      return false;
    if (!(hisIndex == rhs.hisIndex))
      return false;
    if (!(compressMin == rhs.compressMin))
      return false;
    if (!(compressMax == rhs.compressMax))
      return false;
    if (!(lastValue == rhs.lastValue))
      return false;
    if (!(creationDate == rhs.creationDate))
      return false;
    return true;
  }
  bool operator != (const TAGNODE &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TAGNODE & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TAGNODE& obj);
};

void swap(TAGNODE &a, TAGNODE &b);



#endif
